apiVersion: v1
kind: ConfigMap
metadata:
  name: contoso-air-kandanai-config
  namespace: dev
  labels:
    app.kubernetes.io/name: contoso-air-kandanai
    kubernetes.azure.com/generator: devhub
data: